# Configurations
title:            Quartets
longtitle:        Quartets
# author:           Perry van der Zande
author: |
  Lotte Bouma (s3824853)    
  
  Rachelle Bouwens (s3661393)     
  
  Perry van der Zande (s3679799)
description: >
  A Quartets model for LAMAS

version:          1.0
gitbook_version:  3.2.3


# bootstrap: use the remote theme for the site itself
# remote_theme: P-Zande/jekyll-gitbook
# remote_theme:     pages-themes/tactile@v0.2.0
theme: minima #Deze werkt sws
# remote_theme: pages-themes/time-machine@v0.2.0

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
# favicon_path:     ./assets/images/favicon.ico
favicon: /favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - jekyll-remote-theme